import Header from "@/components/general/Header";
import "./globals.css";
import Footer from "@/components/general/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Header />
      <body className="antialiased">{children}</body>
      <Footer />
    </html>
  );
}
